pipeline {
    agent {
        docker { image 'ansible' }
    }

    stages {
        stage("Build") {

           steps {
                dir ("./ansible"){
                    ansiblePlaybook disableHostKeyChecking: true, playbook: './playbook.yml'
                }
            }
        }
    }
}
