pipeline {
    agent {
        docker {
            image 'ansible'
            args '-u root:sudo'
         }
    }

    stages {
        stage("Build") {

           steps {
                dir ("./ansible"){
                    sh 'ansible-playbook ./playbook.yml'
                }
            }
        }
    }
}
